### ISSUE TITLE
NGINX Reverse Proxy / SSL cannot display the Gauges

### ISSUE THREAD

**Issue by nady2804** [gjr80/weewx-steelseries#1]
Hello,
I run a weewx installation with Season (default skin) and the steel gauges skin /ss.
All is working well in local environment. But when i want to have SSL from outside to my internal website.
Therefore i install in a docker station nginx reverse proxy with letsencrypt and want to forward this to SSL.
Means nginx can switch external traffic to my local weewx station which run with local apache2 server.

All is woking but when i want enable SSL then only the skin /ss cannot display the gaues only the header and bottom botton is visible. I have no idea why.
I guess this is a issue regaring SSL and javascript or some other issues in /ss skin. but i habe no knowledge about Javascript.
When i reconfigure the nginx reverseproxy to use only http not https the all including the /ss skin is working....
Can anybody help me to find out why the /ss skin cannot display on a ssl access?

thx
Manfred

**Comment by gjr80** [comment]
Hi,
I am afraid I will not be much help, my knowledge of reverse proxies is virtually nil. My site is secured with a letsencrypt certificate and I use nginx as my web server but without a reverse proxy. The gauges display fine for me. My only suggestion would be to look at the nginx access and error logs, also probably worthwhile having a look at the javascript console in your browser to see if any errors are being thrown there. Failing that you might have some luck posting to a wider audience at the [weewx-user user group](https://groups.google.com/g/weewx-user), this issue list is fairly much only used/seen by me.

**Comment by nady2804** [comment]
Hello, thx for the hint with weewx-user group.
I testet locally on my raspi to enable also the apache2 server to ssl.
But the same issue with the /ss skin is happening therefore i think it's a problem with ssl or no ssl to view the skin.
All other skins are working ???
You wrote that your system also run nginx with ssl? Did you do something other?
The only thing is that i install the skin before i enable ssl can this be a problem i guess no.
When i show source code from the not working site with browser show source code then it looks like the same as without ssl.
No differences no errors...... mhhh only the dynamic gauges are not displayed

**Comment by gjr80** [comment]
I think you hit the nail on the head to start with, it is something affecting JavaScript. The steelseries gauges use JavaScript to render the gauges, so if the rest of the page shows but no gauges it is almost certainty a JavaScript issue. 

My setup is very simple, I just have nginx as my webserver, no Apache and no reverse proxy. I just followed a guide (I cannot remember which) about setting up nginx with letsencrypt and it just worked. From memory nothing special was done.

Did you look at the server logs (including the error log)? The logs might give you a clue as to what is failing. Likewise the browser console so you can see any JavaScript errors.

I am sorry that I am no more help.

**Comment by nady2804** [comment]
i found the problem!
in the /ss/index.html.tmpl file there was a script which loaded with http and i changed that to https:// 
now it's working....
 
  <script src="https://code.jquery.com/jquery-1.11.1.min.js"></script>

**Comment by gjr80** [comment]
Good to hear you found the problem. I use a php page to display my gauges and it loads jquery with https. As an experiment I just changed that to http and as expected the gauges don't render, the error was very obvious in the browser console:
```
Blocked loading mixed active content “http://code.jquery.com/jquery-1.12.4.min.js"
```
Provided it does not interfere with non-SSL operation I will look into having the jquery load changed from http to https.
